options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - gcloud
    - functions
    - deploy
    - chat
    - --runtime=python39
    - --trigger-http
    - --entry-point=chat
    - --allow-unauthenticated
