options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - chat
      - --runtime=python39
      - --trigger-http
      - --entry-point=chat
      - --allow-unauthenticated
