
options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - anu
  - --runtime
  - python310
  - --trigger-http
  - --allow-unauthenticated
